import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pages/Home.module.scss'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>My Little Garden | Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Lorem ipsum dolor sit amet.</h1>
      <div className={styles.main_container}>
        <div className={styles.left_block}>
          <div>
            <h2>Lorem ipsum dolor sit amet.</h2>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore vel corrupti ab architecto vitae enim ipsam, fugit explicabo animi vero dolorum ex fuga ducimus? Tenetur vero voluptas quo quod amet suscipit, quis tempora at aperiam placeat mollitia iusto. Pariatur, odit iusto. Nesciunt, iste repudiandae. Necessitatibus incidunt distinctio voluptatibus fugiat tempore!</p>
          </div>     
          <div>
            <h2>Lorem ipsum dolor sit amet consectetur adipisicing.</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium dolorum, ex id reiciendis quibusdam architecto odio consectetur veniam unde pariatur facere harum, officiis iure! Architecto?</p>
          </div>
          <div>
            <h2>Lorem, ipsum dolor.</h2>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptas tempore sequi ex perspiciatis, in omnis consequuntur laudantium veritatis, perferendis fuga laboriosam accusamus ut, porro incidunt rem repudiandae dignissimos tenetur minima minus recusandae repellat! Ipsum fugit soluta delectus ipsa excepturi sint facere corrupti? Ipsa incidunt asperiores, aperiam dolores placeat autem modi?</p>
          </div>
        </div>
        <div className={styles.right_block}>
          <Image src="/../public/img/seed.jpeg" alt="garden" height="100%" width="100%" layout='responsive' objectFit='contain'/>
        </div>
      </div>
    </div>
  )
}
